### ISSUE TITLE
ServerChatEvent IllegalArgumentException: Illegal group reference

### ISSUE THREAD

**Issue by viveleroi** [hsyyid/EssentialCmds#35] opened 2016-01-17 04:13 UTC
Every chat event triggers the following error in the console. Version 6.7

```
[21:25:09] [Server thread/ERROR] [Sponge]: Could not pass ServerChatEvent to Plugin{id=EssentialCmds, name=EssentialCmds, version=6.7-fc115bc}
java.lang.IllegalArgumentException: Illegal group reference
        at java.util.regex.Matcher.appendReplacement(Matcher.java:857) ~[?:1.8.0_65]
        at java.util.regex.Matcher.replaceFirst(Matcher.java:1004) ~[?:1.8.0_65]
        at java.lang.String.replaceFirst(String.java:2178) ~[?:1.8.0_65]
        at io.github.hsyyid.essentialcmds.listeners.MessageSinkListener.onMessage(MessageSinkListener.java:200) ~[MessageSinkListener.class:6.7]
        at org.spongepowered.common.event.listener.ChatListener_MessageSinkListener_onMessage28.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8-1577-3.1.0-BETA-1025]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:233) [SpongeModEventManager.class:1.8-1577-3.1.0-BETA-1025]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:193) [SpongeModEventManager.class:1.8-1577-3.1.0-BETA-1025]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:70) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:58) [EventBus.class:?]
        at net.minecraft.network.NetHandlerPlayServer.injectChatEvent(NetHandlerPlayServer.java:86) [rj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:796) [rj.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_180757_a(SourceFile:37) [lu.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [lu.class:?]
        at net.minecraft.network.PacketThreadUtil$1.onProcessPacket(SourceFile:110) [ih.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_65]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_65]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```

**Comment by hsyyid** [comment] 2016-01-17 07:55
You need to update

**Comment by viveleroi** [comment] 2016-01-17 20:21
This still occurs with 6.9c.

```
[14:20:04] [Server thread/ERROR] [Sponge]: Could not pass ServerChatEvent to Plugin{id=EssentialCmds, name=EssentialCmds, version=6.9-55b6757}
java.lang.IllegalArgumentException: Illegal group reference
    at java.util.regex.Matcher.appendReplacement(Matcher.java:857) ~[?:1.8.0_65]
    at java.util.regex.Matcher.replaceFirst(Matcher.java:1004) ~[?:1.8.0_65]
    at java.lang.String.replaceFirst(String.java:2178) ~[?:1.8.0_65]
    at io.github.hsyyid.essentialcmds.listeners.MessageSinkListener.onMessage(MessageSinkListener.java:201) ~[MessageSinkListener.class:6.9]
    at org.spongepowered.common.event.listener.ChatListener_MessageSinkListener_onMessage30.handle(Unknown Source) ~[?:?]
    at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8.9-1694-3.1.0-BETA-1060]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:233) [SpongeModEventManager.class:1.8.9-1694-3.1.0-BETA-1060]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:193) [SpongeModEventManager.class:1.8.9-1694-3.1.0-BETA-1060]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:70) [EventBus.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:58) [EventBus.class:?]
    at net.minecraft.network.NetHandlerPlayServer.injectChatEvent(NetHandlerPlayServer.java:91) [lm.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:793) [lm.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
    at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:106) [PacketUtil.class:1.8.9-1694-3.1.0-BETA-1060]
    at net.minecraft.network.PacketThreadUtil$1.onProcessPacket(SourceFile:51) [fh$1.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_65]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_65]
    at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```

**Comment by hsyyid** [comment] 2016-01-17 22:18
@viveleroi What version of PermissionsEx are you running?

**Comment by viveleroi** [comment] 2016-01-17 22:21
PermissionsEx v2.0-SNAPSHOT - downloaded roughly a week ago. Shall I update?

**Comment by hsyyid** [comment] 2016-01-17 22:45
@viveleroi Yeah try updating it.

Also, what SpongeVanilla/SpongeForge are you running?

**Comment by viveleroi** [comment] 2016-01-17 22:47
The last build of PEX was from Jan 2, which I have.

Using spongeforge-1.8.9-1694-3.1.0-BETA-1060. Yesterday we were on build 1035.

**Comment by hsyyid** [comment] 2016-01-19 21:24
Could not reproduce this

**Comment by viveleroi** [comment] 2016-01-19 22:01
Looking through the code I'm realizing that this is a regex problem. In `MessageSinkListener` I don't think you're always going to be getting what the code expects because of other chat plugins. 

For example we have a chat plugin I've started porting which listens to the `MessageChannelEvent.Chat` event, intercepts the message, cancels the event, and sends the message to players in specific channels.

That plugin port was started before message sinks/channels were a thing so it really needs work still, but I don't believe that's a factor with the regex problem.

**Comment by hsyyid** [comment] 2016-01-19 22:15
@viveleroi My listener should be among the first called.

**Comment by viveleroi** [comment] 2016-01-24 17:01
I believe this only happens when a player with a "$" in their suffix chats. Our custom chat plugin formats their message with prefix/suffix (and colors not visible here)

```
[g] LeadMod ickyacky $: test
```

I'm 95% sure that the error only occurs when players with this suffix enter a message.

**Comment by viveleroi** [comment] 2016-01-24 17:02
I didn't release you may have fixed this, will test v7 now.

**Comment by viveleroi** [comment] 2016-01-30 19:59
This still occurs with 7.2e. Any chat message sent by a player with a dollar sign in their suffix causes this error. Until MessageChannels properly send the command source rather than null, our custom chat plugin is stuck doing it the old fashioned way with capture the message event, formatting the text, and re-sending it.

**Comment by hsyyid** [comment] 2016-01-30 20:14
I'll test this further.

**Comment by hsyyid** [comment] 2016-02-15 06:31
I fully tested it, fixed a few issues today, and believe all should be fixed now.

**Closed as completed by hsyyid** 2016-02-15 06:31 UTC
Labels: bug, high priority, needs testing
