### ISSUE TITLE
PositionOutOfBoundsException

### ISSUE THREAD

**Issue by KumaGetsu** [hsyyid/EssentialCmds#81] opened 2016-03-30 20:59 UTC
When logging into game while having left with GameMode 1

http://paste.ubuntu.com/15562960/

**Comment by hsyyid** [comment] 2016-03-30 21:20
Seems like a bug with safelogin. I am looking into it now.

**Comment by hsyyid** [comment] 2016-05-22 19:36
It was caused by an issue in the TeleportHelper, fixed in https://github.com/SpongePowered/SpongeCommon/pull/740

**Closed as completed** 2016-05-23 15:52 UTC
Labels: bug, high priority
